{-# OPTIONS --cubical --safe #-}

-- Derived layer over the TokenAlgebra interface: every lemma below is
-- proved from the record FIELDS alone (plus the cubical library) — no
-- import of S4dot2.SortedPosition.  Names and statement shapes mirror
-- SortedPosition verbatim (so a future facade can re-export them under
-- the same spelling), with the operation dictionary
--   merge → _∪_ , insertToken → insert , [_] → sing , ∅ → ε ,
--   _∈Pos_ → _∈ᵖ_ , _∉Pos_ → _∉ᵖ_ (defined here).

module S4dot2.TokenAlgebra.Derived where

open import Cubical.Foundations.Prelude
  using (Type; _≡_; refl; sym; _∙_; cong; subst; isSet)
  -- Type₀ is not a real exported name: it is generated by Agda's
  -- subscripted-sort mechanism whenever the renamed base name `Type`
  -- is in scope, so importing `Type` suffices.
open import Cubical.Data.Empty as Empty
  using ()
open import Cubical.Data.List
  using (List; []; _∷_)
open import Cubical.Data.Sum as Sum
  using (_⊎_; inl; inr)
open import Cubical.Relation.Nullary
  using (Dec; yes; no; ¬_; Discrete→isSet)

open import S4dot2.TokenAlgebra.Interface

module DerivedLaws (TA : TokenAlgebra) where
  open TokenAlgebra TA

  -- Non-membership (mirror of SortedPosition._∉Pos_)
  _∉ᵖ_ : Token → Pos → Type₀
  x ∉ᵖ s = ¬ (x ∈ᵖ s)

  -- ===========================================================================
  -- 1. Subset relation (pointwise, definitionally SortedPosition:275)
  -- ===========================================================================

  _⊑_ : Pos → Pos → Type₀
  s ⊑ t = ∀ y → y ∈ᵖ s → y ∈ᵖ t

  -- ===========================================================================
  -- 2. Upper bounds, monotonicity, absorption
  -- ===========================================================================

  ⊑-merge-l : ∀ s t → s ⊑ (s ∪ t)
  ⊑-merge-l s t y y∈s = ∈∪-introˡ y s t y∈s

  ⊑-merge-r : ∀ s t → t ⊑ (s ∪ t)
  ⊑-merge-r s t y y∈t = ∈∪-introʳ y s t y∈t

  merge-⊑-mono : ∀ {s s' t t'} → s ⊑ s' → t ⊑ t' → (s ∪ t) ⊑ (s' ∪ t')
  merge-⊑-mono {s} {s'} {t} {t'} s⊑s' t⊑t' y y∈ =
    Sum.rec (λ y∈s → ∈∪-introˡ y s' t' (s⊑s' y y∈s))
            (λ y∈t → ∈∪-introʳ y s' t' (t⊑t' y y∈t))
            (∈∪-elim y s t y∈)

  -- s ⊑ t → s ∪ t ≡ t (s adds nothing new); posExt does the antisymmetry work
  merge-absorb-⊑ : ∀ s t → s ⊑ t → (s ∪ t) ≡ t
  merge-absorb-⊑ s t s⊑t =
    posExt (s ∪ t) t
      (λ y y∈ → Sum.rec (s⊑t y) (λ y∈t → y∈t) (∈∪-elim y s t y∈))
      (λ y y∈t → ∈∪-introʳ y s t y∈t)

  -- Antisymmetry is the posExt field verbatim (SortedPosition:632 name)
  ⊑-antisym : ∀ s t → s ⊑ t → t ⊑ s → s ≡ t
  ⊑-antisym = posExt

  -- ===========================================================================
  -- 3. Left unit (right unit ∪-idr is a field)
  -- ===========================================================================

  merge-∅-l : ∀ s → (ε ∪ s) ≡ s
  merge-∅-l s = ∪-comm ε s ∙ ∪-idr s

  -- ===========================================================================
  -- 4. Non-membership preservation
  -- ===========================================================================

  ∉Pos-merge : ∀ {x s t} → x ∉ᵖ s → x ∉ᵖ t → x ∉ᵖ (s ∪ t)
  ∉Pos-merge {x} {s} {t} x∉s x∉t x∈ = Sum.rec x∉s x∉t (∈∪-elim x s t x∈)

  ∉Pos-remove : ∀ {x} z s → x ∉ᵖ s → x ∉ᵖ (remove z s)
  ∉Pos-remove {x} z s x∉s x∈rem = x∉s (remove-∈-elim x z s x∈rem)

  -- The removed token is gone (new helper; base of the remove-sing chain)
  ¬∈-remove-self : ∀ x s → x ∉ᵖ (remove x s)
  ¬∈-remove-self x s x∈rem = remove-∈-neq x x s x∈rem refl

  -- ===========================================================================
  -- 5. insert laws (insert is not primitive membership-wise: everything is
  --    rewritten along insert-∪-sing : s ∪ sing x ≡ insert x s)
  -- ===========================================================================

  ∈Pos-insertToken : ∀ x y s → y ∈ᵖ (insert x s) → (y ≡ x) ⊎ (y ∈ᵖ s)
  ∈Pos-insertToken x y s y∈ins =
    Sum.rec (λ y∈s → inr y∈s)
            (λ y∈sing → inl (∈sing-elim y x y∈sing))
            (∈∪-elim y s (sing x)
              -- transport membership back along insert-∪-sing
              (subst (y ∈ᵖ_) (sym (insert-∪-sing s x)) y∈ins))

  insertToken-∈Pos : ∀ x y s → (y ≡ x) ⊎ (y ∈ᵖ s) → y ∈ᵖ (insert x s)
  insertToken-∈Pos x y s choice =
    subst (y ∈ᵖ_) (insert-∪-sing s x)
      (Sum.rec (λ y≡x → ∈∪-introʳ y s (sing x)
                          (subst (_∈ᵖ sing x) (sym y≡x) (∈sing-intro x)))
               (λ y∈s → ∈∪-introˡ y s (sing x) y∈s)
               choice)

  ∉Pos-insertToken : ∀ x y s → y ∉ᵖ s → ¬ (y ≡ x) → y ∉ᵖ (insert x s)
  ∉Pos-insertToken x y s y∉s y≢x y∈ins =
    Sum.rec y≢x y∉s (∈Pos-insertToken x y s y∈ins)

  -- Inserting an element already present is the identity
  insertToken-∈Pos-id : ∀ x s → x ∈ᵖ s → insert x s ≡ s
  insertToken-∈Pos-id x s x∈s =
    posExt (insert x s) s
      (λ y y∈ → Sum.rec (λ y≡x → subst (_∈ᵖ s) (sym y≡x) x∈s)
                        (λ y∈s → y∈s)
                        (∈Pos-insertToken x y s y∈))
      (λ y y∈s → insertToken-∈Pos x y s (inr y∈s))

  -- ===========================================================================
  -- 6. remove/insert/merge interaction (all via posExt double inclusion)
  -- ===========================================================================

  remove-insertToken : ∀ x s → x ∉ᵖ s → remove x (insert x s) ≡ s
  remove-insertToken x s x∉s =
    posExt (remove x (insert x s)) s fwd bwd
    where
    fwd : ∀ y → y ∈ᵖ remove x (insert x s) → y ∈ᵖ s
    fwd y y∈rem =
      Sum.rec (λ y≡x → Empty.rec (remove-∈-neq y x (insert x s) y∈rem (sym y≡x)))
              (λ y∈s → y∈s)
              (∈Pos-insertToken x y s (remove-∈-elim y x (insert x s) y∈rem))
    bwd : ∀ y → y ∈ᵖ s → y ∈ᵖ remove x (insert x s)
    bwd y y∈s =
      ∈-remove-intro y x (insert x s)
        (insertToken-∈Pos x y s (inr y∈s))
        (λ x≡y → x∉s (subst (_∈ᵖ s) (sym x≡y) y∈s))

  remove-insertToken-neq : ∀ z x s → ¬ (z ≡ x)
    → remove z (insert x s) ≡ insert x (remove z s)
  remove-insertToken-neq z x s z≢x =
    posExt (remove z (insert x s)) (insert x (remove z s)) fwd bwd
    where
    fwd : ∀ y → y ∈ᵖ remove z (insert x s) → y ∈ᵖ insert x (remove z s)
    fwd y y∈rem =
      Sum.rec (λ y≡x → insertToken-∈Pos x y (remove z s) (inl y≡x))
              (λ y∈s → insertToken-∈Pos x y (remove z s)
                         (inr (∈-remove-intro y z s y∈s
                                (remove-∈-neq y z (insert x s) y∈rem))))
              (∈Pos-insertToken x y s (remove-∈-elim y z (insert x s) y∈rem))
    bwd : ∀ y → y ∈ᵖ insert x (remove z s) → y ∈ᵖ remove z (insert x s)
    bwd y y∈ins =
      Sum.rec (λ y≡x → ∈-remove-intro y z (insert x s)
                         (insertToken-∈Pos x y s (inl y≡x))
                         (λ z≡y → z≢x (z≡y ∙ y≡x)))
              (λ y∈rem → ∈-remove-intro y z (insert x s)
                           (insertToken-∈Pos x y s
                             (inr (remove-∈-elim y z s y∈rem)))
                           (remove-∈-neq y z s y∈rem))
              (∈Pos-insertToken x y (remove z s) y∈ins)

  remove-insertToken-same : ∀ y r → remove y (insert y r) ≡ remove y r
  remove-insertToken-same y r =
    posExt (remove y (insert y r)) (remove y r) fwd bwd
    where
    fwd : ∀ t → t ∈ᵖ remove y (insert y r) → t ∈ᵖ remove y r
    fwd t t∈rem =
      Sum.rec (λ t≡y → Empty.rec (remove-∈-neq t y (insert y r) t∈rem (sym t≡y)))
              (λ t∈r → ∈-remove-intro t y r t∈r
                         (remove-∈-neq t y (insert y r) t∈rem))
              (∈Pos-insertToken y t r (remove-∈-elim t y (insert y r) t∈rem))
    bwd : ∀ t → t ∈ᵖ remove y r → t ∈ᵖ remove y (insert y r)
    bwd t t∈rem =
      ∈-remove-intro t y (insert y r)
        (insertToken-∈Pos y t r (inr (remove-∈-elim t y r t∈rem)))
        (remove-∈-neq t y r t∈rem)

  merge-insertToken-l : ∀ x s t → ((insert x s) ∪ t) ≡ insert x (s ∪ t)
  merge-insertToken-l x s t =
    posExt ((insert x s) ∪ t) (insert x (s ∪ t)) fwd bwd
    where
    fwd : ∀ y → y ∈ᵖ ((insert x s) ∪ t) → y ∈ᵖ insert x (s ∪ t)
    fwd y y∈ =
      Sum.rec
        (λ y∈ins → Sum.rec
           (λ y≡x → insertToken-∈Pos x y (s ∪ t) (inl y≡x))
           (λ y∈s → insertToken-∈Pos x y (s ∪ t) (inr (∈∪-introˡ y s t y∈s)))
           (∈Pos-insertToken x y s y∈ins))
        (λ y∈t → insertToken-∈Pos x y (s ∪ t) (inr (∈∪-introʳ y s t y∈t)))
        (∈∪-elim y (insert x s) t y∈)
    bwd : ∀ y → y ∈ᵖ insert x (s ∪ t) → y ∈ᵖ ((insert x s) ∪ t)
    bwd y y∈ =
      Sum.rec
        (λ y≡x → ∈∪-introˡ y (insert x s) t (insertToken-∈Pos x y s (inl y≡x)))
        (λ y∈st → Sum.rec
           (λ y∈s → ∈∪-introˡ y (insert x s) t (insertToken-∈Pos x y s (inr y∈s)))
           (λ y∈t → ∈∪-introʳ y (insert x s) t y∈t)
           (∈∪-elim y s t y∈st))
        (∈Pos-insertToken x y (s ∪ t) y∈)

  -- ===========================================================================
  -- 7. Removing the singleton's own token empties it
  -- ===========================================================================

  remove-sing-self : ∀ x → remove x (sing x) ≡ ε
  remove-sing-self x =
    posExt (remove x (sing x)) ε
      (λ y y∈rem → Empty.rec
         (remove-∈-neq y x (sing x) y∈rem
           (sym (∈sing-elim y x (remove-∈-elim y x (sing x) y∈rem)))))
      (λ y y∈ε → Empty.rec (¬∈ε y y∈ε))

  -- ===========================================================================
  -- 8. Token substitution on positions (SortedPosition:121)
  -- ===========================================================================

  substTokenPos : Token → Pos → Pos → Pos
  substTokenPos x t s = (remove x s) ∪ t

  -- Key lemma for mix (SortedPosition:158)
  substTokenPos-insert : ∀ x s t → x ∉ᵖ s
    → substTokenPos x t (insert x s) ≡ (s ∪ t)
  substTokenPos-insert x s t x∉s = cong (_∪ t) (remove-insertToken x s x∉s)

  -- Eigenposition preserved under substitution (SortedPosition:607)
  substTokenPos-insertToken-neq : ∀ z y s t → ¬ (z ≡ y)
    → substTokenPos z t (insert y s) ≡ insert y (substTokenPos z t s)
  substTokenPos-insertToken-neq z y s t z≢y =
    cong (_∪ t) (remove-insertToken-neq z y s z≢y)
      ∙ merge-insertToken-l y (remove z s) t

  -- Non-membership preserved by substitution (SortedPosition:410)
  ∉Pos-substTokenPos : ∀ {x} z t s → x ∉ᵖ s → x ∉ᵖ t → x ∉ᵖ (substTokenPos z t s)
  ∉Pos-substTokenPos z t s x∉s x∉t = ∉Pos-merge (∉Pos-remove z s x∉s) x∉t

  -- ===========================================================================
  -- 9. Positions form a set (Hedberg on the decidable equality field)
  -- ===========================================================================

  isSetPos : isSet Pos
  isSetPos = Discrete→isSet discretePos

  -- ===========================================================================
  -- 10. Decidable subset (via listability: iterate toList s against _∈ᵖ?_)
  -- ===========================================================================

  private
    -- Case split on list membership (avoids forced-variable pattern lambdas)
    ∈L-case : ∀ {x y : Token} {xs : List Token}
      → y ∈L (x ∷ xs) → (y ≡ x) ⊎ (y ∈L xs)
    ∈L-case hereL = inl refl
    ∈L-case (thereL m) = inr m

    -- Decide "every token of the list is in t" by recursion on the list
    allInPos? : ∀ (xs : List Token) (t : Pos)
      → Dec (∀ y → y ∈L xs → y ∈ᵖ t)
    allInPos? [] t = yes (λ y ())
    allInPos? (x ∷ xs) t with x ∈ᵖ? t
    ... | no x∉t = no (λ all → x∉t (all x hereL))
    ... | yes x∈t with allInPos? xs t
    ...   | yes rest = yes (λ y y∈ →
              Sum.rec (λ y≡x → subst (_∈ᵖ t) (sym y≡x) x∈t)
                      (rest y)
                      (∈L-case y∈))
    ...   | no ¬rest = no (λ all → ¬rest (λ y m → all y (thereL m)))

  _⊑?_ : (s t : Pos) → Dec (s ⊑ t)
  s ⊑? t with allInPos? (toList s) t
  ... | yes all = yes (λ y y∈s → all y (∈→toList y s y∈s))
  ... | no ¬all = no (λ s⊑t → ¬all (λ y y∈L → s⊑t y (toList→∈ y s y∈L)))
